### ISSUE TITLE
Communication protocol specification

### ISSUE THREAD

**Issue by psviderski** [DannyDeGaspari/Samsung-HVAC-buscontrol#1]
It is really cool that you managed to reverse engineer the communication protocol of your Samsung aircon. I'm also interested in replacing my wall-mounted wired remote controller with my custom microcontroller that I can connect to my home automation system. According to the [service manual](https://dvmdownload.com/upload/product/76/download/MWRWE10_MWR-WE10%20Service%20Manual.pdf) for my remote controller it uses rs485 bus to communicate with the AC unit.
Can you please share any information you found?

**Comment by DannyDeGaspari** [comment]
Hi Pavel, I will update this repository. Nice to hear that other people have the same idea about the control of airco units.
