### ISSUE TITLE
Which GPIO pins to use?

### ISSUE THREAD

**Issue by guybridge** [DannyDeGaspari/Samsung-HVAC-buscontrol#11]
This is more a hardware question.

Most tutorials regarding the MAX485 get you to init the GPIO pins on DE/RE as HIGH

however in the code you don't init them ?

Thx

**Comment by DannyDeGaspari** [comment]
It actually doesn't matter if the signalling is on RS485 levels or anything else, for the Pi's OS it is just a UART which is properly initialized at startup. I used the dedicated UART pins on the GPIO header.

**Comment by guybridge** [comment]
OK thank you.
