### ISSUE TITLE
How to determine the indoor units address?

### ISSUE THREAD

**Issue by guybridge** [DannyDeGaspari/Samsung-HVAC-buscontrol#12]
In your code you use 0x20 and 0x21 for the indoor units address.

0x84 appears to be the wired remote's address too

Will this be the same for mine?

How could I perform a search on the bus for my unit? - I only have one.

**Comment by DannyDeGaspari** [comment]
This is the auto enumeration that the system does at power up. It scans the bus for units and assigns them these addresses in my case. The disadvantage is that sometimes after a power fail the addresses of the units get swapped which is annoying if you want to change settings of only one unit.
But from the installation manual it must be possible to assign fixed addresses somewhere on the units motherboards.
You can find out the addresses of your unit by monitoring the traffic on the comms and analysing the sender and the receiver address in the message.

**Comment by guybridge** [comment]
thx
