### ISSUE TITLE
Wrong Command 52 temperature deserialization (bit 6 secret ;-)

### ISSUE THREAD

**Issue by pavelchuchma** [DannyDeGaspari/Samsung-HVAC-buscontrol#17]
Hi Danny,
your doc tells about temperature in Command 52: 
```
bit 5-0 : set temperature - 9
bit 6 : always set to '1' ?
```
In reality it should be:
```
bit 6-0 : set temperature + 55
```
Detected & tested on my [java HVAC Controller project](https://github.com/pavelchuchma/hvac-controller/tree/master#readme) during hot summer when AC air output was 8°C but original deserialization read it wrongly as 72°C.

Feel free to see [this fix](https://github.com/pavelchuchma/hvac-controller/commit/ece3ba04b577d1a716d0d0a0884764da9966738b), especially the test method at the end.

**Comment by DannyDeGaspari** [comment]
Thanks for mentioning this ! I will update my docs.
