### ISSUE TITLE
samsung communication question

### ISSUE THREAD

**Issue by tommysong89** [DannyDeGaspari/Samsung-HVAC-buscontrol#2]
Sound like samsung buscontrol is not like modbus protocol .
I try samsung MWR-TH00 wired remote controller, and catch the code through pressing fan mode:
32 84 20 A0 1F 00 58 01 F4 00 00 00 D9 34  auto->low
32 84 20 A0 1F 00 98 01 F4 00 00 00 76 34  low->middle
32 84 20 A0 1F 00 B8 05 A3 00 00 00 59 A2 FE  middle->higth
32 84 20 A0 1F 00 18 01 F4 00 00 00 F6 69 FF higth->auto
The last two codes is not ending by 0x34.
I set the baud rate 2400, 8E1. Do I set anything wrong?

**Comment by DannyDeGaspari** [comment]
Hi,
First, the message length must always be 14 chars. Your last 2 messages have 15 chars, thats already strange.
Second, on char position 7 and 8 (start counting from 0) I see in your third message '05 A3', I never saw these codes on that position with that command, so I don't know what they mean. (Check my command table xls document)

To me it looks like your messages are mixed up with parts of another message for whatever reason. Did you use my serial_dump script ? What is your HVAC setup, do you have one unit or more ? In my case I have 2 units connected to the remote.
What hardware do you use to read the HVAC serial line ?

**Comment by tommysong89** [comment]
Thank you so much for your kindly response.
I get pull out wired remote controller's RS485 transceiver Tx and Rx, and connect to PC through COMtoUSB tool. Thus, I can get wired remote controller send out message and message received, print these messages by serial tool in PC. In my case, I have one unit connected to the remote.

**Comment by DannyDeGaspari** [comment]
Hi,
Do you filter the messages before displaying? Normally one would also see the responses from unit to wired remote. It might be interesting to look at the responses too to understand what is happening. Do you always get the same result if you redo the test ?

**Comment by tommysong89** [comment]
HI, I redo the test, and the message is not the same. I check my UART configuration and find out the parity is none, it should be even. I set the wrong UART configuration.
Thanks a lot to help me find the print problem!
Does wired remote command, for instance 32 84 20 A0 1F 00 18 00 F4 00 00 00 F7 34, always follow the broadcast message(like 32 84 AD D1 00 00 FF FF FF 00 00 00 07 34)?
If I only send command without broadcast, does the unit execute this command?

**Comment by DannyDeGaspari** [comment]
> Does wired remote command, for instance 32 84 20 A0 1F 00 18 00 F4 00 00 00 F7 34, always follow the broadcast message(like 32 84 AD D1 00 00 FF FF FF 00 00 00 07 34)?

That is what I see on my system.

> If I only send command without broadcast, does the unit execute this command?

Yes it does. I don't know why the broadcast is needed or what it is doing.

Good luck controlling your system.
