### ISSUE TITLE
Crc calculation

### ISSUE THREAD

**Issue by ofarukcebir** [DannyDeGaspari/Samsung-HVAC-buscontrol#4]

**Comment by DannyDeGaspari** [comment]
Looks like the package starts and ends with the same codes as for the wired protocol. I do not know how CRC or checksum is calculated for remote control. But a quick search leads me to [this](https://github.com/crankyoldgit/IRremoteESP8266). Maybe you can find the info there ?

Danny

**Comment by ofarukcebir** [comment]
i am talking about the wired remoot also. 
by the way i found it.
crc calculation bytes starts with 4th byte.  polynomial = 0x1021, inital value = 0x00

**Comment by DannyDeGaspari** [comment]
Thanks for sharing. By the way which wired remote are you using ? I'm using the MWR-WE10 controller.

**Comment by ofarukcebir** [comment]
mwr-sh10rn
