### ISSUE TITLE
Command52 improvements

### ISSUE THREAD

**Issue by pavelchuchma** [DannyDeGaspari/Samsung-HVAC-buscontrol#8]
Nice work! I did almost the same reverse engineering in 2017 and wrote own controller library in java. I found your project recently and it motivated me to publish my [lib too](https://github.com/pavelchuchma/hvac-controller). I took few flags from your understanding of Command52 packet. Thanks for it! Especially for the documentation :-)

And I found one minor mistake here: 
* Temperature bytes (1, 2, 3 and 8) of Command 52 are 6 bits wide (0-5) instead of 5 (0-4) as you describe. My Samsung heat pump (NS071SDXEA) reports output air temperatures up to 53 degrees and such value is too big for 5 bits.

And one improvement:
* Command 52, data byte 3 is *output air temperature*. And byte 8 is (reserved for) probably another internal thermometer. Both values are always equal in my case.

Both updated and verified in my lib: Output air temperature continuously grows from 18-53 degrees after device start. Manually measured air temperature on heat pump output corresponds to this value.

**Comment by DannyDeGaspari** [comment]
Thank you very much!
I'll update my documentation according to your info.

**Comment by DannyDeGaspari** [comment]
I checked the values of byte 8 in command 52. In my case the value is not equal to byte 3 and always a little bit higher when the unit is switched on. The other unit which is off has byte 8 value a little bit lower then byte 3.

**Comment by pavelchuchma** [comment]
Thanks for fast reaction :-)
The message structure is probably designed for 2 internal thermometers. Most probably, some units have 2 thermometers and are reporting values separately. And other units (like my) have only one thermometer and they are putting this single value to both fields to keep message compatibility.

btw: don't forget to update bit mask [here](https://github.com/DannyDeGaspari/Samsung-HVAC-buscontrol/blob/master/ac_status.py#L46)
